sonar.sources=backend,App,frontend/src
sonar.exclusions=**/coverage/**,**/dist/**,**/build/**,**/node_modules/**,**/*.bak
sonar.issue.ignore.multicriteria=jsxUnknownProperties
sonar.issue.ignore.multicriteria.jsxUnknownProperties.ruleKey=javascript:S6747
sonar.issue.ignore.multicriteria.jsxUnknownProperties.resourceKey=frontend/src/**/*.jsx
