sonar.sources=backend,App,frontend/src
sonar.exclusions=**/coverage/**,**/dist/**,**/build/**,**/node_modules/**,**/*.bak,frontend/src/**/*.jsx
sonar.issue.ignore.multicriteria=jsxUnknownProperties,storageTaint
sonar.issue.ignore.multicriteria.jsxUnknownProperties.ruleKey=javascript:S6747
sonar.issue.ignore.multicriteria.jsxUnknownProperties.resourceKey=**/*.jsx
sonar.issue.ignore.multicriteria.storageTaint.ruleKey=jssecurity:S8475
sonar.issue.ignore.multicriteria.storageTaint.resourceKey=frontend/src/utils/storage.js
